name: Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Use GitHub environment for protection rules and approvals
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set environment variables
        id: vars
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          echo "environment=$ENV" >> $GITHUB_OUTPUT
          
          # Map environment to client ID
          case $ENV in
            dev)
              echo "client_id=${{ secrets.AZURE_CLIENT_ID_DEV }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "client_id=${{ secrets.AZURE_CLIENT_ID_STAGING }}" >> $GITHUB_OUTPUT
              ;;
            production)
              echo "client_id=${{ secrets.AZURE_CLIENT_ID_PROD }}" >> $GITHUB_OUTPUT
              ;;
          esac
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ steps.vars.outputs.client_id }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Deploy to Azure
        run: |
          echo "Deploying to ${{ steps.vars.outputs.environment }}"
          # Your deployment commands here
          az account show
          
          # Example: Deploy to App Service
          # az webapp deployment source config-zip \
          #   --resource-group myResourceGroup \
          #   --name myAppName-${{ steps.vars.outputs.environment }} \
          #   --src ./app.zip
